[build]
  base = "/"
  command = "cd ${PWD} && npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "10.2.4"
  CI = "false" 