[build]
  base = "/"
  command = "npm install --production=false && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.1"
  CI = "false"
  NPM_CONFIG_PRODUCTION = "false" 